### ISSUE TITLE
[LOCALIZATION] 🇰🇷 Korean Translations

### ISSUE THREAD

**Issue by avikantz** [avikantz/ikea-word-games#10]
Korean translations and local data would be greatly appreciated.

[Reference](https://github.com/avikantz/ikea-word-games/blob/main/CONTRIBUTING.MD#adding-a-new-locale)

**Comment by c2lv** [comment]
Is it ok if I add korean translate file at `src/app/i18n/locales/kr/default.json`default.json`?

**Comment by avikantz** [comment]
@c2lv Hi, yes, that would be the location. Please refer to the documentation and #4 or #39 to generate local names of the products using the script.

**Comment by c2lv** [comment]
I add it in `en-KR`. Can you check it?
#46

**Comment by avikantz** [comment]
Fixed by #46
