### ISSUE TITLE
[BUG] Unable to click on product names after successful guess in Bildval

### ISSUE THREAD

**Issue by avikantz** [avikantz/ikea-word-games#21]
**Describe the bug**

After a successful guess in Bildval, the item name is not clickable. This works for all the other options, or all if you fail a guess.

**To Reproduce**

1. Navigate to Bildval, start a round
2. Make a successful guess
3. The product name is not clickable

**Expected behavior**

Product name should be clickable.

**Screenshots**

https://github.com/avikantz/ikea-word-games/assets/7699509/ff21f2aa-cac5-479b-b938-51a125dfe5e5

**Additional context**

Suspect it has something to do with the confetti.

**Comment by AnuMessi10** [comment]
Hi @avikantz, I am new to this and would like to contribute, can you assign this to me?

**Comment by avikantz** [comment]
Hej @AnuMessi10, sure!
