### ISSUE TITLE
[BUG] Unable to click on product names after successful guess in Ordval

### ISSUE THREAD

**Issue by avikantz** [avikantz/ikea-word-games#24]
**Describe the bug**

After a successful guess in Ordval, the item name is not clickable. This works for all the other options, or all if you fail a guess.

**To Reproduce**

1. Navigate to Ordval, start a round
2. Make a successful guess
3. The product name is not clickable

**Expected behavior**

Product name should be clickable.

**Screenshots**

https://github.com/avikantz/ikea-word-games/assets/7699509/79a76f1b-081f-460f-a24f-a494567ae139

**Additional context**

Suspect it has something to do with the confetti. Refer to #21 for a similar issue on Bildval

**Comment by DIlkhush00** [comment]
Hi @avikantz, I would like to work on this issue. Can you assign it to me?

**Comment by avikantz** [comment]
Hi, @DIlkhush00 sure!

**Comment by DIlkhush00** [comment]
Thank you!
