### ISSUE TITLE
[FEATURE] Better on screen keyboard feedback (Jumble)

### ISSUE THREAD

**Issue by avikantz** [avikantz/ikea-word-games#26]
**Is your feature request related to a problem? Please describe.**

Typing on mobile on-screen keyboard on Jumble is a mess.

<img width="570" alt="image" src="https://github.com/avikantz/ikea-word-games/assets/7699509/663f1105-b019-4de2-97a6-803e7e5784e4">

**Describe the solution you'd like**

Feedback on press

- On tap, it currently reverts to hover state, and does not "press-out". This is not very nice.
- perhaps we could have a better press feedback (e.g. native mobile keyboards)

![Screenshot_1696332677](https://github.com/avikantz/ikea-word-games/assets/7699509/17dad989-aafb-4745-be98-7e7bc70da2b7)

**Describe alternatives you've considered**

Typing with the native device keyboard is a mess when you've validating inputs. This is not an option (Even more popular games like wordle use a on screen keyboard)

**Comment by AnuMessi10** [comment]
Hi @avikantz it's me again, let me know if you can assign this to me. Cheers!

**Comment by avikantz** [comment]
> Hi @avikantz it's me again, let me know if you can assign this to me. Cheers!

Welcome back, sure!

**Comment by AnuMessi10** [comment]
Hi @avikantz does this issue require any further action?

**Comment by avikantz** [comment]
> Hi @avikantz does this issue require any further action?

Huh, thought it will close automatically. Closing this, thanks @AnuMessi10
