### ISSUE TITLE
[FEATURE] Expose product image on Ordval

### ISSUE THREAD

**Issue by avikantz** [avikantz/ikea-word-games#28]
**Is your feature request related to a problem? Please describe.**

[Ordval](https://ikeawordgames.com/ordval) is missing product images because they can give away the solution fairly easily.

But when a guess (correct/incorrect) is made, images could be shown.

**Describe the solution you'd like**

Product images to be shown after a guess is made in ordval.

Creative liberties on how to layout the guess option in `components/ordval`, such that layout shifts are prevented when a guess is made (the item shouldn't resize itself to accommodate the image)

An use case is to blur the image till a guess is made, but even with blurring some products could be identified

Perhaps a combination of filters could achieve this neatly.

| Example question | Example guess |
|-------------------|----------------|
| <img width="1566" alt="Screenshot 2023-10-03 at 5 24 45 PM" src="https://github.com/avikantz/ikea-word-games/assets/7699509/828b37dd-ac11-4fdd-a901-c9669cda26ca"> | <img width="1566" alt="Screenshot 2023-10-03 at 5 22 15 PM" src="https://github.com/avikantz/ikea-word-games/assets/7699509/a18b352f-56de-4b5c-b26d-d853412259bd"> |

**Comment by nidble** [comment]
hello @avikantz, can I work on this?

**Comment by avikantz** [comment]
> hello @avikantz, can I work on this?

Hello again, sure!
