### ISSUE TITLE
[FEATURE] Disable non-solution characters from Jumble

### ISSUE THREAD

**Issue by avikantz** [avikantz/ikea-word-games#37]
**Is your feature request related to a problem? Please describe.**

Jumble currently allows **all** characters to be typed using keyboard and on-screen keyboard. This is not ideal, as most characters will never be part of the solution.

**Describe the solution you'd like**

- The input for not to allow non-solution characters for entry. A beep/jiggle or something to signify invalid input (This is currently done only at the end of submission).
- The on-screen keyboard to visually show that the character cannot be typed (button disabled).

**Describe alternatives you've considered**

N/A

**Additional context**

| State of things | Example solution |
|----------------|------------------|
| ![Screenshot 2023-10-14 at 6 32 13 PM](https://github.com/avikantz/ikea-word-games/assets/7699509/905e8b2d-1ae7-446a-90e8-5c4f592c6bbd) | ![Screenshot 2023-10-14 at 6 31 58 PM](https://github.com/avikantz/ikea-word-games/assets/7699509/562a8c01-5e12-4565-8440-b561eaebb47b) |

**Comment by paulkim26** [comment]
Neat project! I'd be interested in taking on this issue. I'm thinking of implementing a `disabledKeys`  property for the `WordInput` component which would allow Jumble to specifically disable non-playable characters. How does that sound?

**Comment by avikantz** [comment]
Hej @paulkim26. Thank you for the interest in the project.

Sounds good. Although `WordInput` has a `targetValue` string being passed to it. Disabled keys can possibly be inferred from it. I'll leave you to take a call.

**Comment by paulkim26** [comment]
Hi @avikantz , well noted about `targetValue` - will look into how to best leverage that property. Appreciate the heads up 👍
