### ISSUE TITLE
[BUG] Extra characters can be entered via the Jumble visual keyboard beyond the character limit

### ISSUE THREAD

**Issue by paulkim26** [avikantz/ikea-word-games#41]
**Describe the bug**

In Jumble, the user can enter additional characters into the visual keyboard even if the character limit in the input field is reached. These extra characters cannot be seen but are present - you can tell because you can backspace them.

**To Reproduce**

1. Go to https://ikeawordgames.com/en/jumble/easy.
2. Open the visual keyboard.
3. Fill out the input field, then add a couple extra characters.
4. Press backspace on the visual keyboard. Nothing changes.
5. Only upon pressing backspace more times, will the changes in the input field be visible.

**Expected behavior**

It should not be possible to enter extra characters into the input field. If the input field is filled and a backspace is pressed, the user would expect to see characters being deleted.

**Screenshots**

Result after pressing the backspace on the visual keyboard after the input field is filled. Note that the input field is still full (has 4 letters).
![image](https://github.com/avikantz/ikea-word-games/assets/45007945/5ae91560-4604-4046-9f0a-922155af82c0)

**Desktop (please complete the following information):**

 - OS: Windows 11
 - Browser: Chrome
 - Version: 117.0.5938.152 (Official Build) (64-bit)

**Additional context**

If this issue is accepted, I would greatly appreciate it if was labelled as a `hacktoberfest` issue.

**Comment by avikantz** [comment]
Ahh, good eye!
