### ISSUE TITLE
[LOCALIZATION] 🇫🇮 Finnish Translations

### ISSUE THREAD

**Issue by avikantz** [avikantz/ikea-word-games#6]
Finnish translations and local data would be greatly appreciated.

[Reference](https://github.com/avikantz/ikea-word-games/blob/main/CONTRIBUTING.MD#adding-a-new-locale)

**Comment by minna-xD** [comment]
Good evening and happy Hacktoberfest! 🎃 I would like to take on this task.

**Comment by avikantz** [comment]
Hej @minna-xD, thank you for your interest in the project. I have assigned the issue to you. Please let me know if you have any questions. Happy hacktoberfest 🎃!
